#!/usr/bin/env bash
set -e
[ -n "$SOLENV_DEBUG" ] && set -x

# Provide solenv completions
if [ "$1" = "--complete" ]; then
  exec solenv-rehash --complete
fi

# When solenv shell integration is enabled, delegate to solenv-rehash,
# then tell the shell to empty its command lookup cache.
solenv-rehash
echo "hash -r 2>/dev/null || true"
