#!/usr/bin/env bash
# Summary: List all solc versions that contain the given executable
# Usage: solenv whence [--path] <command>

set -e
[ -n "$SOLENV_DEBUG" ] && set -x

# Provide solenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec solenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  solenv-versions --bare | while read version; do
    path="$(solenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

SOLENV_COMMAND="$1"
if [ -z "$SOLENV_COMMAND" ]; then
  solenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$SOLENV_COMMAND")"
[ -n "$result" ] && echo "$result"
