#!/usr/bin/env bash
# Summary: Show the current solc version
set -e
[ -n "$SOLENV_DEBUG" ] && set -x

if [ -z "$SOLENV_VERSION" ]; then
  SOLENV_VERSION_FILE="$(solenv-version-file)"
  SOLENV_VERSION="$(solenv-version-file-read "$SOLENV_VERSION_FILE" || true)"
fi

if [ -z "$SOLENV_VERSION" ] || [ "$SOLENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${SOLENV_ROOT}/versions/${version}" ]
}

if version_exists "$SOLENV_VERSION"; then
  echo "$SOLENV_VERSION"
elif version_exists "${SOLENV_VERSION#solc-}"; then
  { echo "warning: ignoring extraneous \`solc-' prefix in version \`${SOLENV_VERSION}'"
    echo "         (set by $(solenv-version-origin))"
  } >&2
  echo "${SOLENV_VERSION#solc-}"
else
  echo "solenv: version \`$SOLENV_VERSION' is not installed" >&2
  exit 1
fi
