#!/usr/bin/env bash
# Summary: List all solc versions available to solenv
# Usage: solenv versions [--bare]
#
# Lists all solc versions found in `$SOLENV_ROOT/versions/*'.

set -e
[ -n "$SOLENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(solenv-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(solenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && SOLENV_VERSION=system solenv-which solc >/dev/null 2>&1; then
  print_version system
fi

for path in "${SOLENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
