#!/usr/bin/env bash
# Usage: solenv completions <command> [arg1 arg2...]

set -e
[ -n "$SOLENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  solenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "solenv-$COMMAND" || command -v "solenv-sh-$COMMAND")"
if grep -i "^\([#%]\|--\|//\) provide solenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
